### ISSUE TITLE
How to use flight planner and flight directors?

### ISSUE THREAD

**Issue by ArthurZhou** [Octol1ttle/FlightAssistant#8]

**Comment by Octol1ttle** [comment]
Flight Directors will be *armed* when pressing the `Toggle Flight Directors` keybind (`Numpad 1` by default). The visual indicator for this is `FD` appearing on either the upper or lower right of the HUD, depending on version.

Flight Directors require that a destination point is present in order to appear:
- A destination can be selected manually
  - In 1.0 (Modrinth releases), this can be done with the `/flas nav <destination X> <destination Z>` and `/flas alt <target altitude>` commands
  - In 2.0, this can be done with the `/flas mcp heading <target heading>` and `/flas mcp altitude <target altitude>` commands
- A destination is provided via the flight plan (2.0 only)
  - For this, the commands `/flas plan <add/remove/insert/replace/clear>` can be used with arguments being provided as needed. After you've finished creating your flight plan, you must *execute* it by using `/flas plan execute`.
